### ISSUE TITLE
Missing Livereload

### ISSUE THREAD

**Issue by riderx** [StarkShang/vite-plugin-chrome-extension#21]
i just switch to vite, i was on webpack arch before and livereload was working.
file where generated with UUID in the name, for content script it was still needed a reload of the extension and the page.
But now i need to remove the extension to make update .

**Comment by Toumash** [comment]
[Hot reload does not work in Chrome Manifest V3](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/pYtdXH0f46E), therefor this issue should be closed

**Comment by riderx** [comment]
Thanks for the feedback, can you link to the doc to know why ?

**Comment by Toumash** [comment]
The answer is here: https://stackoverflow.com/a/65976345/3711660
Im not really sure about the whole thing, because there is very little to none on this topic, but im trying to get [this code to run](https://github.com/sidehustlelab/chrome-manifest-v3-webpack-hotreload-template/issues/1) without luck to check if this is a real issue or not.
